# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Portafolio de Notebooks"
author: Alicia Gil Matute
logo: ""

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/aliciagilmatute/jupyter-notebooks-hugo  # Online location of your book
  path_to_book: . # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ""   # opcional
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  extra_navbar: ""    # quita la firma "Powered by Jupyter Book"
  home_page_in_navbar: true
